### PR TITLE
Added root domain search functionality

### PR DESCRIPTION
**Pull request by mcharris**
There was a need for the ability when looking up a entry to also include other items with the same root domain.

For example: oauth.foo.com and sso.foo.com should pull up the same keys. So the best way I thought was to add a checkbox in the settings where you can include all root domain entries. So looking up oauth.foo.com will return keys with foo.com and everything underneath the domain foo.com. 

I did set this as default disabled to not change behavior of current installations.

This could also solve issue reported by @slunak 

Attached is a non-signed build with my fix. 
[MacPassHTTP.mpplugin.zip](https://github.com/MacPass/MacPassHTTP/files/1640481/MacPassHTTP.mpplugin.zip)

### CODE REVIEW

**Comment by mstarke** [comment]
I just took a look into the KeePassHTTP source and it seems the matching uses host based url matching so this should work as well in MacPassHTTP out of the box if the matchin algorithm is correct.

Can you try to change the algorithm in https://github.com/MacPass/MacPassHTTP/blob/7320f8d6ba65d9a2dd459afa152e345cbbf10c99/MacPassHTTP/MPHServerDelegate.m#L175 to match host based? You can take a look at the handlers in KeePassHTTP as well to get a grip on how the original does it: https://github.com/pfn/keepasshttp/blob/b9a6813bfc9ccc9618938249c1bfff744a28ca44/KeePassHttp/Handlers.cs#L270

**Comment by mcharris** [comment]
There is possibly a disconnect here because the name of the variables. The `url` variable in the code is actually the host (FQDN). That line that you are referencing is the exact line I changed. Every other change that was done was for that one line :D. 

So essentially if the URL that gets hit on the browser is `https://1.a.foo.com/login?var1=blarg` then what is passed into the MPHServerDelegate is `url=1.a.foo.com` and `domainUrl=foo.com` with the new option enabled. I do think that the variable names need to change to match what they actually are. 

I did take a look at the original and the KeePassHTTP and it is using entirly different logic. It also uses the submit URL at part of its lookup. This would mean that this would have to be passed as well. Unfortunately this will have to come from KeePassHTTPKit but from your other responses I didnt think you wanted to alter the kit too much. Personally I think there is a major flaw with the KeePassHTTPKit. All context for the lookup need to be passed all the way down to what ever is actually doing the logic. In this case it is MPHServerDelegate. But in 

https://github.com/MacPass/KeePassHTTPKit/blob/91a08d0c0fe4be50a96e057b3590c23d3b5c9878/KeePassHTTPKit/Handlers/KPHHandler.m#L107

you will notice that the url is converted from the NSURL to the host as a NSString. If we want to mimic 100% how the original KeePassHTTP then we need to pass the entire request object down. Since that is a major revision of the both the KeePassHTTPKit and the MacPassHTTP I think this pull request is a good middle ground.

**Comment by mstarke** [comment]
Thanks for the clarification. I have to add that I have never dived into the code since I only ported and wrapped it. It might even be useful to remove the split-up between KeePassHTTPKit and merge all the code directly into MacPassHTTP since there is no real benefit of modularisation. I did it that way to make the code base simple without changing too much on the original.

If you like go ahead and start ripping it all up and putting it together in a better fashion. The thing that bugs me the most is the additional setting which is completely missing from KeePassHTTP

**Comment by mcharris** [comment]
The only reason I added the option was so that it would affect others. I am completely ok with removing the option all together and forcing same root domain lookups. It returns more results that the user might want. At least it does from me. I am coming from another application called KyPass that is clunky but decent lookup for a browser integration standpoint. 

I do think that bringing in the server and killing the KeePassHTTPKit framework is the better option. Its too complicated for such a simple task. 

By the way, if you look at the options for the original https://raw.githubusercontent.com/pfn/keepasshttp/master/documentation/images/options-general.png
This setting is there but under a different name :D

**Comment by mstarke** [comment]
Do you mean settings 2? Setting 4 is only related to the protocol not the url rest of the url.
Might I ask, why you closed the PR?

**Pull request closed without merging**
